### ISSUE TITLE
Switching over to spaces

### ISSUE THREAD

**Issue by nieldlr** [bufferapp/javascript-style-guide#3]
Hi guys,

I remember sometime ago we talked about switching over [to spaces for PHP](https://github.com/bufferapp/buffer-php-style-guide/issues/1). What do you guys think of doing the same for JS and go ahead starting to use spaces (2 spaces) as default?

Here's an example plan:

1) We change .editorconfig to use spaces instead of tabs & send an email to the team if they aren't using [editorconfig](http://editorconfig.com) to start using spaces instead.
2) Whenever you're in a file that uses tabs, convert it to spaces. Here's a [nice Sublime guide](http://css-tricks.com/changing-spaces-tabs-sublime-text/)! My thinking here is that it might be smoother to convert the whole file, since we might have mismatches going on in terms of layout. What do you guys think?
3) Git Blame will be preserved by the -w flag :)

Maybe I'm over simplifying things here and totally missing something big! Would to hear your thoughts :)

**Comment by djfarrelly** [comment]
Closing this one out! We've updated it in the [`README.md`](https://github.com/bufferapp/javascript-style-guide#whitespace) and it's been updated in the `.editorconfig` in the buffer-web repo
